version: "3.9"

services:
  tn_client:
    container_name: tn_client
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 3005
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5712:3005"
    environment:
      - VITE_API_URL=http://172.23.0.2:3000/api/v1
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    external: true
    driver: bridge
    attachable: true
