version: "3.9"

services:
  tn_client:
    container_name: tn_client
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 3005
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5712:3005"
    env_file:
      - .env
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    external: true
    driver: bridge
